"""
Django settings for trucking_ops project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url

BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", 'django-insecure-n8=o0o@h83^1$=1)^gic81tjyb=$#7ky+=z-yw)g0)%1_br7eh')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False") == "True"

ALLOWED_HOSTS = ["localhost", "127.0.0.1", ".railway.app"]
if os.environ.get("ALLOWED_HOST"):
    ALLOWED_HOSTS.append(os.environ["ALLOWED_HOST"])
CSRF_TRUSTED_ORIGINS = ["https://*.railway.app"]
if os.environ.get("ALLOWED_HOST"):
    CSRF_TRUSTED_ORIGINS.append("https://" + os.environ["ALLOWED_HOST"])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'operations',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'operations.middleware.CurrentUserMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'trucking_ops.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'operations.context.nav',
            ],
        },
    },
]

WSGI_APPLICATION = 'trucking_ops.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}", conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
}

# Uploaded documents (BOL, POD, receipts, company/truck docs, logos).
# By default they go to the local disk / Railway volume (MEDIA_DIR).
# If Cloudflare R2 (or S3) keys are set in Railway Variables, uploads go there
# instead — safe, permanent cloud storage that survives server resets.
MEDIA_URL = '/media/'
MEDIA_ROOT = os.environ.get('MEDIA_DIR') or (BASE_DIR / 'media')

_R2_KEY = os.environ.get("R2_ACCESS_KEY_ID", "").strip()
_R2_SECRET = os.environ.get("R2_SECRET_ACCESS_KEY", "").strip()
_R2_BUCKET = os.environ.get("R2_BUCKET", "").strip()
_R2_ENDPOINT = os.environ.get("R2_ENDPOINT", "").strip()  # https://<account>.r2.cloudflarestorage.com
_R2_PUBLIC = os.environ.get("R2_PUBLIC_URL", "").strip()  # optional public bucket URL

if _R2_KEY and _R2_SECRET and _R2_BUCKET and _R2_ENDPOINT:
    STORAGES["default"] = {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "bucket_name": _R2_BUCKET,
            "access_key": _R2_KEY,
            "secret_key": _R2_SECRET,
            "endpoint_url": _R2_ENDPOINT,
            "region_name": "auto",
            "signature_version": "s3v4",
            "file_overwrite": False,
            "default_acl": None,
            "querystring_auth": True,       # signed links so private docs stay private
            "querystring_expire": 3600,     # view links valid for 1 hour
            **({"custom_domain": _R2_PUBLIC.replace("https://", "").replace("http://", "")}
               if _R2_PUBLIC else {}),
        },
    }

# Email notifications (optional). Set EMAIL_HOST etc. in Railway Variables to enable.
# Without them, notifications stay in-app only (no errors).
EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
if EMAIL_HOST:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
    EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
    # Port 465 uses SSL; port 587 uses TLS. Pick automatically from the port,
    # or force with EMAIL_SECURITY = "ssl" / "tls" in Railway.
    _sec = os.environ.get("EMAIL_SECURITY", "").lower()
    if _sec == "ssl" or (not _sec and EMAIL_PORT == 465):
        EMAIL_USE_SSL = True
        EMAIL_USE_TLS = False
    else:
        EMAIL_USE_TLS = True
        EMAIL_USE_SSL = False
    EMAIL_TIMEOUT = 20
else:
    EMAIL_BACKEND = "django.core.mail.backends.dummy.EmailBackend"
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "notifications@pure99inc.com")

# Send login-required redirects (and the 404->home bounce) to the real login page.
LOGIN_URL = "/admin/login/"
LOGIN_REDIRECT_URL = "/dashboard/"
