from django.contrib.auth import views as auth_views
from django.views.static import serve as _serve
from django.conf import settings
from django.contrib import admin
from django.urls import path, re_path
from django.views.generic import RedirectView
from operations import views

urlpatterns = [
    path("app/chat/poll/", views.chat_poll, name="chat_poll"),
    path("app/chat/send/", views.chat_send, name="chat_send"),
    path("app/chat/handoff/", views.chat_handoff_save, name="chat_handoff_save"),
    path("app/messages/", views.message_board, name="message_board"),
    path("app/messages/add-note/", views.add_note, name="add_note"),
    path("app/messages/<int:pk>/delete/", views.delete_message, name="delete_message"),
    path("admin/", admin.site.urls),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("app/tasks/", views.tasks_page, name="tasks_page"),
    path("app/board/", views.team_board, name="team_board"),
    path("app/board/note/", views.team_note_add, name="team_note_add"),
    path("app/board/note/<int:pk>/pin/", views.team_note_pin, name="team_note_pin"),
    path("app/tasks/new/", views.task_create, name="task_create"),
    path("app/tasks/<int:pk>/status/", views.task_status, name="task_status"),
    path("app/performance/", views.performance_page, name="performance_page"),
    path("app/pay/", views.driver_pay, name="driver_pay"),
    path("app/pay/new/", views.driver_pay_new, name="driver_pay_new"),
    path("app/pay/<int:pk>/", views.driver_pay_detail, name="driver_pay_detail"),
    path("app/pay/<int:pk>/pdf/", views.driver_pay_pdf, name="driver_pay_pdf"),
    path("app/pay/<int:pk>/email/", views.driver_pay_email, name="driver_pay_email"),
    path("app/performance/note/", views.perf_note_add, name="perf_note_add"),
    path("app/performance/<str:kind>/<int:pk>/", views.performance_detail, name="performance_detail"),
    path("reports/driver/<int:pk>/", views.driver_report, name="driver_report"),
    path("reports/driver/<int:pk>/pdf/", views.driver_report_pdf, name="driver_report_pdf"),
    path("c/<slug:slug>/", views.portal_login, name="portal_login"),
    path("login/", views.portal_login, name="portal_login_generic"),
    path("portfolio/", views.portfolio, name="portfolio"),
    # custom app sections
    path("app/loads/", views.app_loads, name="app_loads"),
    path("app/loads/import/", views.load_import, name="load_import"),
    path("app/loads/new/", views.app_load_new, name="app_load_new"),
    path("app/loads/estimate-miles/", views.estimate_miles_api, name="estimate_miles_api"),
    path("app/loads/deadhead/", views.deadhead_api, name="deadhead_api"),
    path("app/fmcsa/lookup/", views.fmcsa_lookup, name="fmcsa_lookup"),
    path("app/company/new/", views.company_new, name="company_new"),
    path("app/company/access/", views.company_access, name="company_access"),
    path("app/company/documents/", views.company_docs, name="company_docs"),
    path("app/loads/from-ratecon/", views.load_from_ratecon, name="load_from_ratecon"),
    path("app/loads/<int:pk>/", views.app_load_detail, name="app_load_detail"),
    path("app/loads/<int:pk>/doc/", views.load_doc_upload, name="load_doc_upload"),
    path("app/drivers/", views.app_drivers, name="app_drivers"),
    path("app/drivers/<int:pk>/", views.app_driver_detail, name="app_driver_detail"),
    path("app/drivers/<int:pk>/dqf/", views.app_driver_dqf, name="app_driver_dqf"),
    path("dqf/<int:doc_id>/approve/", views.dqf_approve, name="dqf_approve"),
    path("dqf/<int:doc_id>/reject/", views.dqf_reject, name="dqf_reject"),
    path("driver/<str:token>/", views.driver_upload, name="driver_upload"),

    path("app/vehicles/", views.app_vehicles, name="app_vehicles"),
    path("reports/maintenance/", views.fleet_maintenance, name="fleet_maintenance"),
    path("reports/maintenance/pdf/", views.fleet_maintenance_pdf, name="fleet_maintenance_pdf"),
    path("app/vehicles/<int:pk>/", views.app_vehicle_detail, name="app_vehicle_detail"),
    path("app/vehicles/<int:pk>/doc/", views.vehicle_doc_upload, name="vehicle_doc_upload"),
    path("app/vehicles/<int:pk>/photo/", views.vehicle_photo_upload, name="vehicle_photo_upload"),
    path("app/vehicles/<int:pk>/photo/<int:photo_id>/delete/", views.vehicle_photo_delete, name="vehicle_photo_delete"),
    path("app/vehicles/<int:pk>/doc/<int:doc_id>/delete/", views.vehicle_doc_delete, name="vehicle_doc_delete"),
    path("app/vehicles/<int:pk>/service/add/", views.maintenance_add, name="maintenance_add"),
    path("app/vehicles/<int:pk>/report/", views.vehicle_report_pdf, name="vehicle_report_pdf"),
    path("app/vehicles/<int:pk>/report/email/", views.email_vehicle_report, name="email_vehicle_report"),
    path("app/hiring/", views.app_hiring, name="app_hiring"),
    path("app/hiring/<int:pk>/", views.applicant_detail, name="applicant_detail"),
    path("app/dqf/", views.dqf_list, name="dqf_list"),
    path("app/dqf/<int:pk>/", views.dqf_detail, name="dqf_detail"),
    path("app/reviews/", views.doc_review_queue, name="doc_review_queue"),
    path("app/compliance-center/", views.compliance_center, name="compliance_center"),
    path("app/audit-center/", views.audit_center, name="audit_center"),
    path("app/email-document/", views.email_document, name="email_document"),
    path("app/driver/<int:pk>/audit-pdf/", views.driver_audit_pdf, name="driver_audit_pdf"),
    path("audit/<str:token>/", views.auditor_view, name="auditor_view"),
    path("app/brokers/", views.app_brokers, name="app_brokers"),
    path("app/fuel/", views.app_fuel, name="app_fuel"),
    path("app/fuel/add/", views.fuel_add, name="fuel_add"),
    path("app/fuel/<int:pk>/receipt/", views.fuel_receipt, name="fuel_receipt"),
    path("app/fuel/import/", views.fuel_import, name="fuel_import"),
    path("app/fuel/pdf/", views.fuel_report_pdf, name="fuel_report_pdf"),
    path("app/team/", views.app_team, name="app_team"),
    path("app/team/add/", views.team_add, name="team_add"),
    path("app/team/<int:pk>/toggle/", views.team_toggle_active, name="team_toggle_active"),
    path("app/team/<int:pk>/remove/", views.team_delete, name="team_delete"),
    path("app/team/<int:pk>/edit/", views.team_edit, name="team_edit"),
    path("app/team/<int:pk>/send-reset/", views.team_send_reset, name="team_send_reset"),
    path("app/timesheet/", views.app_timesheet, name="app_timesheet"),
    path("app/clock/", views.clock_toggle, name="clock_toggle"),

    path("app/compliance/", views.app_compliance, name="app_compliance"),
    path("app/accounting/", views.app_accounting, name="app_accounting"),
    path("app/accounting/expense/add/", views.expense_add, name="expense_add"),
    path("app/accounting/expense/<int:pk>/receipt/", views.expense_receipt, name="expense_receipt"),
    path("app/billing/", views.app_billing, name="app_billing"),
    path("app/billing/new/", views.invoice_create, name="invoice_create"),
    path("app/billing/<int:pk>/", views.invoice_detail, name="invoice_detail"),
    path("app/billing/<int:pk>/pay/", views.payment_add, name="payment_add"),
    path("app/billing/<int:pk>/print/", views.invoice_print, name="invoice_print"),

    # reports
    path("reports/", views.reports_index, name="reports"),
    path("reports/builder/", views.report_builder, name="report_builder"),
    path("reports/pnl/", views.pnl_report, name="pnl"),
    path("reports/pnl/truck/", views.per_truck_pnl, name="per_truck_pnl"),
    path("reports/truck/<int:pk>/", views.truck_detail, name="truck_detail"),
    path("reports/truck/<int:pk>/pdf/", views.truck_detail_pdf, name="truck_detail_pdf"),
    path("reports/pnl/truck/pdf/", views.per_truck_pnl_pdf, name="per_truck_pnl_pdf"),
    path("reports/tax/", views.tax_report, name="tax"),
    path("reports/factoring/", views.factoring_report, name="factoring"),
    path("reports/factoring/aging/", views.factoring_aging, name="factoring_aging"),
    path("reports/factoring/aging/pdf/", views.factoring_aging_pdf, name="factoring_aging_pdf"),
    path("reports/compliance/", views.compliance_report, name="compliance"),
    path("reports/activity/", views.activity_feed, name="activity"),
    path("tax/1099/<int:driver_id>/", views.generate_1099, name="generate_1099"),
    path("tax/1099/<int:driver_id>/pdf/", views.generate_1099_pdf, name="generate_1099_pdf"),
    path("tax/1099/<int:driver_id>/email/", views.email_1099, name="email_1099"),
    path("hiring/links/", views.hiring_links, name="hiring_links"),
    path("apply/done/", views.apply_thanks, name="apply_thanks"),
    path("apply/<str:token>/", views.apply_view, name="apply"),
    path("media/<path:path>", views.protected_media, name="protected_media"),
    path("", RedirectView.as_view(url="/dashboard/", permanent=False)),
]

handler404 = "operations.views.go_home"

urlpatterns += [
    re_path(r"^media/(?P<path>.*)$", _serve, {"document_root": settings.MEDIA_ROOT}),
]

urlpatterns += [
    path("password-reset/", auth_views.PasswordResetView.as_view(), name="password_reset"),
    path("password-reset/done/", auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("reset/done/", auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]
