# Generated by Django 6.0.7 on 2026-08-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_load_bill_of_lading_load_invoice_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(default='Fuel', help_text='Pick a suggestion or type your own category.', max_length=60),
        ),
    ]
