# Generated by Django 6.0.7 on 2026-08-05 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_company_apply_token_applicant_compliancedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('load_created', 'Load booked'), ('payment_updated', 'Load payment status changed'), ('application_received', 'New driver application'), ('expense_added', 'Expense added'), ('settlement_created', 'Driver settlement created'), ('doc_expiring', 'Document expiring soon')], max_length=40, unique=True)),
                ('in_app', models.BooleanField(default=True, verbose_name='In-app')),
                ('email', models.BooleanField(default=False, verbose_name='Email')),
                ('sms', models.BooleanField(default=False, verbose_name='Text (coming soon)')),
            ],
            options={
                'ordering': ['event'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=250, verbose_name='Mailing address'),
        ),
        migrations.AddField(
            model_name='company',
            name='ein',
            field=models.CharField(blank=True, max_length=20, verbose_name='EIN (federal tax ID)'),
        ),
        migrations.AddField(
            model_name='driver',
            name='address',
            field=models.CharField(blank=True, max_length=250, verbose_name='Mailing address'),
        ),
        migrations.AddField(
            model_name='driver',
            name='tax_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tax ID (SSN/EIN, for 1099)'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=20)),
                ('text', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='operations.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
