# Generated by Django 6.0.7 on 2026-08-06 05:03

import secrets
from django.db import migrations, models



def _fill_upload_tokens(apps, schema_editor):
    Driver = apps.get_model("operations", "Driver")
    for d in Driver.objects.filter(upload_token=""):
        d.upload_token = secrets.token_urlsafe(12)
        d.save(update_fields=["upload_token"])


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_activitylog_user_alter_profile_role_timeentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='upload_token',
            field=models.CharField(blank=True, db_index=True, help_text="Used for this driver's private document-upload link.", max_length=32),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='doc_type',
            field=models.CharField(choices=[('cdl', 'CDL license'), ('application', 'Employment application'), ('medical', 'Medical certificate'), ('mvr', 'Motor Vehicle Record (MVR)'), ('annual_review', 'Annual review of driving record'), ('psp', 'PSP report'), ('clearinghouse', 'Clearinghouse query'), ('drug_test', 'Drug / alcohol test'), ('road_test', 'Road test / CDL equivalency'), ('safety_history', 'Safety performance history'), ('eldt', 'ELDT certificate'), ('w9', 'W-9 (contractor)'), ('other', 'Other')], max_length=20),
        ),
        migrations.RunPython(_fill_upload_tokens, _noop),
    ]
