# Generated by Django 6.0.7 on 2026-08-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_invoice_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='last_service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_service_miles',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Odometer at last service'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='next_service_date',
            field=models.DateField(blank=True, null=True, verbose_name='Next service due (date)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='odometer',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Current odometer (miles)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Plate / registration expiry'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='service_interval_miles',
            field=models.PositiveIntegerField(blank=True, help_text='e.g. 25000. Leave blank if you track service by date instead.', null=True, verbose_name='Service interval (miles)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='inspection_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Annual (DOT) inspection expiry'),
        ),
    ]
