# Generated by Django 6.0.7 on 2026-08-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_maintenancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='receipt',
            field=models.FileField(blank=True, upload_to='receipts/', verbose_name='Invoice / receipt'),
        ),
    ]
