# Generated by Django 6.0.7 on 2026-08-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0021_settlement_extra_reimbursement'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='deadhead_miles',
            field=models.PositiveIntegerField(default=0, help_text='Empty miles driven to reach the pickup.', verbose_name='Deadhead (empty) miles'),
        ),
        migrations.AlterField(
            model_name='load',
            name='miles',
            field=models.PositiveIntegerField(default=0, verbose_name='Loaded miles'),
        ),
    ]
