# Generated by Django 6.0.7 on 2026-08-14 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0022_load_deadhead_miles_alter_load_miles'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessor', models.CharField(blank=True, max_length=120, verbose_name='Rental / leasing company')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Contract end date')),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Base rent amount')),
                ('base_period', models.CharField(choices=[('week', 'Per week'), ('month', 'Per month')], default='week', max_length=6)),
                ('per_mile_rate', models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Per-mile rate ($)')),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_contracts', to='operations.company')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='operations.vehicle')),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
    ]
