# Generated by Django 6.0.7 on 2026-08-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0023_rentalcontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='ownership',
            field=models.CharField(choices=[('owned', 'Owned'), ('leased', 'Leased'), ('rented', 'Rented')], default='owned', max_length=8),
        ),
    ]
