# Generated by Django 6.0.7 on 2026-08-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0024_vehicle_ownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='pay_basis',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('daily', 'Daily'), ('per_load', 'Per load')], default='weekly', max_length=10),
        ),
    ]
