# Generated by Django 6.0.7 on 2026-08-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0025_settlement_pay_basis'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='hide_load_amounts',
            field=models.BooleanField(default=False, verbose_name='Hide load $ amounts on this statement'),
        ),
    ]
