# Generated by Django 6.1 on 2026-08-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0029_load_stops'),
    ]

    operations = [
        migrations.AddField(
            model_name='fueltransaction',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='fuel_receipts/', verbose_name='Receipt / invoice'),
        ),
    ]
