# Generated by Django 6.1 on 2026-08-19 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0036_compliancedocument_review_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=120)),
                ('form_version', models.CharField(default='1.0', max_length=20)),
                ('signer_name', models.CharField(max_length=120)),
                ('consent_text', models.TextField(blank=True)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to='operations.applicant')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='operations.company')),
            ],
            options={
                'ordering': ['-signed_at'],
            },
        ),
    ]
