# Generated by Django 6.1 on 2026-08-20 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0041_broker_address_line_broker_city_broker_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='broker_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loads', to='operations.brokeragent'),
        ),
    ]
