# Generated by Django 6.1 on 2026-08-20 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0048_fueltransaction_ifta_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='IftaStateEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('quarter', models.PositiveSmallIntegerField()),
                ('state', models.CharField(max_length=2)),
                ('miles', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0, help_text='State fuel tax rate per gallon for this quarter.', max_digits=6)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ifta_entries', to='operations.company')),
            ],
            options={
                'ordering': ['state'],
                'unique_together': {('company', 'year', 'quarter', 'state')},
            },
        ),
    ]
