# Generated by Django 6.1 on 2026-08-25 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0055_loadstatusevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='in_service_date',
            field=models.DateField(blank=True, help_text='When this physical truck started running for you.', null=True, verbose_name='In service (start) date'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='out_of_service_date',
            field=models.DateField(blank=True, help_text='When this truck was returned / retired.', null=True, verbose_name='Out of service (returned) date'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='replaces',
            field=models.ForeignKey(blank=True, help_text='If this truck replaced a broken-down/returned unit, link it here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by_set', to='operations.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('shop', 'In shop'), ('inactive', 'Inactive'), ('retired', 'Retired / returned')], default='active', max_length=10),
        ),
    ]
