# Generated by Django 6.1 on 2026-08-30 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0056_vehicle_in_service_date_vehicle_out_of_service_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('deduction', 'Deduction'), ('reimbursement', 'Reimbursement')], max_length=14)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='operations.settlement')),
            ],
            options={
                'ordering': ['kind', 'id'],
            },
        ),
    ]
