# Generated by Django 6.1 on 2026-09-11 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0060_loadphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('ownership_pct', models.DecimalField(decimal_places=2, default=0, help_text="This partner's ownership share of the company, e.g. 50.00", max_digits=5, verbose_name='Ownership %')),
                ('email', models.CharField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='operations.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_by_partner',
            field=models.ForeignKey(blank=True, help_text='If a partner paid this out of pocket, who.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_paid', to='operations.partner'),
        ),
        migrations.CreateModel(
            name='PartnerPayback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('method', models.CharField(blank=True, max_length=40)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_paybacks', to='operations.company')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paybacks', to='operations.partner')),
                ('vehicle', models.ForeignKey(blank=True, help_text='Optional: tie this payback to a specific truck.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.vehicle')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
