# Generated by Django 6.1.1 on 2026-09-16 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0063_driver_business_ein'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='hide_load_amounts_on_check',
            field=models.BooleanField(default=False, help_text="If on, the check stub lists the loads but NOT each load's dollar amount.", verbose_name="Hide load $ amounts on this driver's checks"),
        ),
    ]
