# Generated by Django 6.1.1 on 2026-09-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0065_company_check_amount_offset_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='billing_email',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='company',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='company',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_status',
            field=models.CharField(choices=[('trial', 'Free trial'), ('active', 'Active / paid'), ('past_due', 'Past due'), ('canceled', 'Canceled'), ('none', 'None')], default='none', max_length=12),
        ),
        migrations.AddField(
            model_name='company',
            name='trial_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='trial_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
