# Generated by Django 6.1.1 on 2026-09-20 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0077_supportticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=140)),
                ('company_name', models.CharField(blank=True, max_length=160)),
                ('email', models.CharField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('fleet_size', models.CharField(blank=True, max_length=40)),
                ('message', models.TextField(blank=True)),
                ('stage', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('demo', 'Demo scheduled'), ('trial', 'Trialing'), ('won', 'Won / Onboarded'), ('lost', 'Lost')], default='new', max_length=12)),
                ('source', models.CharField(blank=True, max_length=80, verbose_name='Source (utm_source)')),
                ('medium', models.CharField(blank=True, max_length=80, verbose_name='Medium (utm_medium)')),
                ('campaign', models.CharField(blank=True, max_length=120, verbose_name='Campaign (utm_campaign)')),
                ('ad_content', models.CharField(blank=True, max_length=120, verbose_name='Ad (utm_content)')),
                ('term', models.CharField(blank=True, max_length=120, verbose_name='Keyword (utm_term)')),
                ('landing_page', models.CharField(blank=True, max_length=200)),
                ('next_follow_up', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.company')),
                ('owner', models.ForeignKey(blank=True, help_text='Sales person responsible', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='operations.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
