# Generated by Django 6.1.1 on 2026-09-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0078_lead_leadnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_sales_team',
            field=models.BooleanField(default=False, verbose_name='Sales/marketing team (platform side)'),
        ),
    ]
