# Generated by Django 6.0.7 on 2026-08-03 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('mc_number', models.CharField(blank=True, max_length=30, verbose_name='MC number')),
                ('dot_number', models.CharField(blank=True, max_length=30, verbose_name='DOT number')),
                ('ca_number', models.CharField(blank=True, max_length=30, verbose_name='CA number')),
                ('factor', models.CharField(choices=[('RTS', 'RTS Financial'), ('Bobtail', 'Bobtail'), ('Other', 'Other'), ('None', 'No factoring')], default='None', max_length=10)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cdl_number', models.CharField(blank=True, max_length=40, verbose_name='CDL number')),
                ('cdl_class', models.CharField(blank=True, choices=[('A', 'Class A'), ('B', 'Class B'), ('C', 'Class C')], max_length=1, verbose_name='CDL class')),
                ('cdl_expiry', models.DateField(blank=True, null=True, verbose_name='CDL expiry')),
                ('medical_expiry', models.DateField(blank=True, null=True, verbose_name='Medical card expiry')),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('driver_type', models.CharField(choices=[('company', 'Company driver'), ('owner_operator', 'Owner-operator')], default='company', help_text='Owner-operators can see load rates; company drivers see miles only.', max_length=15)),
                ('tax_status', models.CharField(choices=[('w2', 'W-2 employee'), ('1099', '1099 contractor')], default='w2', help_text='1099 contractors get a 1099-NEC; W-2 employees go through payroll.', max_length=5)),
                ('pay_type', models.CharField(choices=[('per_mile', 'Per mile'), ('percentage', 'Percentage of load'), ('salary', 'Salary')], default='per_mile', max_length=12)),
                ('pay_rate', models.DecimalField(decimal_places=2, default=0, help_text='Cents per mile, percent (e.g. 25), or weekly salary amount.', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='operations.company')),
                ('user', models.OneToOneField(blank=True, help_text='Optional login so the driver can see their own loads and pay.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('dispatcher', 'Dispatcher'), ('accountant', 'Accountant'), ('billing', 'Billing'), ('driver', 'Driver')], default='dispatcher', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('companies', models.ManyToManyField(blank=True, help_text='Which companies this person can access. Leave empty for none.', to='operations.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=30)),
                ('make', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('vin', models.CharField(blank=True, max_length=30, verbose_name='VIN')),
                ('plate', models.CharField(blank=True, max_length=20)),
                ('inspection_expiry', models.DateField(blank=True, null=True, verbose_name='Annual inspection expiry')),
                ('status', models.CharField(choices=[('active', 'Active'), ('shop', 'In shop'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='operations.company')),
            ],
            options={
                'ordering': ['unit_number'],
            },
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40, verbose_name='Load / reference #')),
                ('customer', models.CharField(blank=True, max_length=120, verbose_name='Broker / customer')),
                ('origin', models.CharField(max_length=120)),
                ('destination', models.CharField(max_length=120)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('miles', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('dispatched', 'Dispatched'), ('in_transit', 'In transit'), ('delivered', 'Delivered'), ('invoiced', 'Invoiced'), ('paid', 'Paid')], default='booked', max_length=12)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('submitted', 'Submitted to factor'), ('advanced', 'Advanced'), ('reserve_released', 'Reserve released'), ('closed', 'Closed')], default='unpaid', max_length=18)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loads', to='operations.company')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.driver')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.vehicle')),
            ],
            options={
                'ordering': ['-pickup_date'],
            },
        ),
    ]
