# Generated by Django 6.0.7 on 2026-08-03 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='bill_of_lading',
            field=models.FileField(blank=True, upload_to='loads/bol/', verbose_name='Bill of Lading (BOL)'),
        ),
        migrations.AddField(
            model_name='load',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='load',
            name='proof_of_delivery',
            field=models.FileField(blank=True, upload_to='loads/pod/', verbose_name='Proof of Delivery (POD)'),
        ),
        migrations.AddField(
            model_name='load',
            name='rate_confirmation',
            field=models.FileField(blank=True, upload_to='loads/ratecon/'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('fuel', 'Fuel'), ('maintenance', 'Maintenance / repair'), ('insurance', 'Insurance'), ('tolls', 'Tolls'), ('permits', 'Permits / licensing'), ('other', 'Other')], default='fuel', max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vendor', models.CharField(blank=True, max_length=120)),
                ('receipt', models.FileField(blank=True, upload_to='expenses/')),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='operations.company')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.driver')),
                ('load', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.load')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.vehicle')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='operations.company')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='operations.driver')),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
    ]
