# Generated by Django 6.0.7 on 2026-08-03 20:02

import django.db.models.deletion
import secrets
from django.db import migrations, models



def _fill_tokens(apps, schema_editor):
    Company = apps.get_model("operations", "Company")
    for c in Company.objects.filter(apply_token=""):
        c.apply_token = secrets.token_urlsafe(12)
        c.save(update_fields=["apply_token"])


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_alter_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='apply_token',
            field=models.CharField(blank=True, db_index=True, help_text="Used to build this company's public driver-application link.", max_length=32),
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('current_address', models.CharField(blank=True, max_length=200, verbose_name='Current address')),
                ('address_history', models.TextField(blank=True, verbose_name='Address history (last 3 years)')),
                ('cdl_number', models.CharField(blank=True, max_length=40, verbose_name='CDL number')),
                ('cdl_class', models.CharField(blank=True, choices=[('A', 'Class A'), ('B', 'Class B'), ('C', 'Class C')], max_length=1, verbose_name='CDL class')),
                ('cdl_state', models.CharField(blank=True, max_length=20, verbose_name='CDL state')),
                ('years_experience', models.PositiveIntegerField(blank=True, null=True, verbose_name='Years of experience')),
                ('employment_history', models.TextField(blank=True, verbose_name='Employment history (last 10 years)')),
                ('accidents', models.TextField(blank=True, verbose_name='Accident / violation history')),
                ('cdl_file', models.FileField(blank=True, upload_to='applicants/cdl/', verbose_name='CDL (front & back)')),
                ('medical_file', models.FileField(blank=True, upload_to='applicants/medical/', verbose_name='Medical certificate')),
                ('other_file', models.FileField(blank=True, upload_to='applicants/other/', verbose_name='Other document')),
                ('consent', models.BooleanField(default=False, verbose_name='Authorizes MVR, PSP, drug/alcohol & Clearinghouse checks')),
                ('signature', models.CharField(blank=True, max_length=100, verbose_name='Signature (typed full name)')),
                ('stage', models.CharField(choices=[('applied', 'Applied'), ('screening', 'Screening (MVR / PSP)'), ('dq_file', 'DQ file'), ('cleared', 'Cleared / hired'), ('declined', 'Declined')], default='applied', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='operations.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('application', 'Employment application'), ('mvr', 'Motor Vehicle Record (MVR)'), ('medical', 'Medical certificate'), ('clearinghouse', 'Clearinghouse query'), ('drug_test', 'Drug / alcohol test'), ('eldt', 'ELDT certificate'), ('road_test', 'Road test / CDL equivalency'), ('safety_history', 'Safety performance history'), ('w9', 'W-9 (contractor)'), ('other', 'Other')], max_length=20)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Leave blank if this document does not expire.', null=True)),
                ('file', models.FileField(blank=True, upload_to='compliance/')),
                ('verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='operations.company')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='operations.driver')),
            ],
            options={
                'ordering': ['expiry_date'],
            },
        ),
            migrations.RunPython(_fill_tokens, _noop),
    ]
