# Generated by Django 6.0.7 on 2026-08-10 09:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_vehicle_last_service_date_vehicle_last_service_miles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('part', models.CharField(max_length=160, verbose_name='Part / service')),
                ('vendor', models.CharField(blank=True, max_length=120, verbose_name='Shop / vendor')),
                ('odometer', models.PositiveIntegerField(blank=True, null=True, verbose_name='Odometer (miles)')),
                ('parts_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance', to='operations.company')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance', to='operations.vehicle')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
