# Generated by Django 6.0.7 on 2026-08-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_company_email_company_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.FileField(blank=True, help_text="Shown on this company's invoices and reports (PNG or JPG).", null=True, upload_to='company_logos/', verbose_name='Company logo'),
        ),
    ]
