# Generated by Django 6.0.7 on 2026-08-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0015_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(blank=True, help_text="Used in this company's portal link, e.g. /c/roundway", max_length=60),
        ),
    ]
