# Generated by Django 6.0.7 on 2026-08-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0018_teamnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='out_of_pocket',
            field=models.BooleanField(default=False, verbose_name='Driver paid from own pocket (reimburse)'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settlement',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='payment_method',
            field=models.CharField(blank=True, help_text='e.g. Check, Zelle, ACH, Cash', max_length=40),
        ),
        migrations.AddField(
            model_name='settlement',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Check number, Zelle/ACH confirmation, etc.', max_length=60),
        ),
    ]
