# Generated by Django 6.0.7 on 2026-08-13 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0019_expense_out_of_pocket_settlement_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loads', to='operations.settlement'),
        ),
    ]
