# Generated by Django 6.0.7 on 2026-08-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0020_load_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='extra_reimbursement',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Money owed back to the driver not tied to a logged expense.', max_digits=10, verbose_name='Extra reimbursement to driver'),
        ),
    ]
