# Generated by Django 6.0.7 on 2026-08-14 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0026_settlement_hide_load_amounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('registration', 'Registration / Plate'), ('insurance', 'Insurance'), ('inspection', 'Annual / DOT inspection'), ('lease', 'Lease / rental agreement'), ('permit', 'Permit'), ('ifta', 'IFTA'), ('title', 'Title'), ('other', 'Other')], default='other', max_length=15)),
                ('title', models.CharField(blank=True, max_length=140)),
                ('file', models.FileField(upload_to='vehicle_docs/')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry date (optional)')),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_documents', to='operations.company')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='operations.vehicle')),
            ],
            options={
                'ordering': ['expiry_date', 'doc_type'],
            },
        ),
    ]
