# Generated by Django 6.0.7 on 2026-08-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0027_vehicledocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledocument',
            name='custom_type',
            field=models.CharField(blank=True, help_text="Type what kind of document this is, e.g. 'Cab card', 'Lease addendum'.", max_length=60, verbose_name="Custom category (if 'Other')"),
        ),
    ]
