# Generated by Django 6.1 on 2026-08-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0028_vehicledocument_custom_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='stops',
            field=models.TextField(blank=True, help_text='One stop per line, in order.', verbose_name='All stops (multi-stop / LTL)'),
        ),
    ]
