# Generated by Django 6.1 on 2026-08-18 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0030_fueltransaction_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='fmcsa_status',
            field=models.CharField(blank=True, max_length=60, verbose_name='FMCSA operating status'),
        ),
        migrations.AddField(
            model_name='company',
            name='fmcsa_updated',
            field=models.DateField(blank=True, null=True, verbose_name='FMCSA data pulled on'),
        ),
        migrations.AddField(
            model_name='company',
            name='power_units',
            field=models.IntegerField(blank=True, null=True, verbose_name='Power units'),
        ),
        migrations.AddField(
            model_name='company',
            name='safety_rating',
            field=models.CharField(blank=True, max_length=40, verbose_name='FMCSA safety rating'),
        ),
    ]
