# Generated by Django 6.1 on 2026-08-18 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0031_company_fmcsa_status_company_fmcsa_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('mc_authority', 'MC authority letter'), ('coi', 'Certificate of Insurance (COI)'), ('ifta', 'IFTA'), ('mcp', 'MCP letter'), ('w9', 'W-9'), ('noa', 'Notice of Assignment (factoring)'), ('ucr', 'UCR'), ('boc3', 'BOC-3'), ('ein_letter', 'EIN letter'), ('operating_auth', 'Operating authority'), ('other', 'Other')], default='other', max_length=20)),
                ('custom_type', models.CharField(blank=True, max_length=60, verbose_name="Custom category (if 'Other')")),
                ('title', models.CharField(blank=True, max_length=140)),
                ('file', models.FileField(upload_to='company_docs/')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry date (optional)')),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_documents', to='operations.company')),
            ],
            options={
                'ordering': ['expiry_date', 'doc_type'],
            },
        ),
    ]
