# Generated by Django 6.1 on 2026-08-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0032_companydocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='factor_other',
            field=models.CharField(blank=True, max_length=80, verbose_name="Factoring company (if 'Other')"),
        ),
        migrations.AlterField(
            model_name='company',
            name='factor',
            field=models.CharField(choices=[('None', 'No factoring'), ('RTS', 'RTS Financial'), ('Bobtail', 'Bobtail'), ('TAFS', 'TAFS'), ('Apex', 'Apex Capital'), ('TBS', 'TBS Factoring'), ('OTR', 'OTR Solutions'), ('Triumph', 'Triumph Business Capital'), ('eCapital', 'eCapital'), ('Riviera', 'Riviera Finance'), ('Porter', 'Porter Freight Funding'), ('Compass', 'Compass Funding Solutions'), ('England', 'England Carrier Services'), ('Thunder', 'Thunder Funding'), ('Phoenix', 'Phoenix Capital Group'), ('Single', 'Single Point Capital'), ('Love', "Love's / TFS"), ('Other', 'Other (type below)')], default='None', max_length=20),
        ),
    ]
