# Generated by Django 6.1 on 2026-08-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0033_company_factor_other_alter_company_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='dba_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='DBA / doing-business-as name'),
        ),
        migrations.AddField(
            model_name='company',
            name='state_code',
            field=models.CharField(blank=True, max_length=2, verbose_name='State (2-letter)'),
        ),
        migrations.AddField(
            model_name='company',
            name='state_tax_no',
            field=models.CharField(blank=True, max_length=30, verbose_name='State tax / payer state no.'),
        ),
    ]
