# Generated by Django 6.1 on 2026-08-19 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0034_company_dba_name_company_state_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Recruiter handling this applicant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applicants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicant',
            name='converted_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_applicant', to='operations.driver'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='decision_reason',
            field=models.CharField(blank=True, help_text='Reason for approval or rejection.', max_length=200),
        ),
        migrations.AddField(
            model_name='applicant',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated labels.', max_length=200),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='stage',
            field=models.CharField(choices=[('invited', 'Invited'), ('started', 'Application started'), ('incomplete', 'Application incomplete'), ('applied', 'Submitted'), ('review', 'Pending review'), ('background', 'Background checks pending'), ('docs_missing', 'Documents missing'), ('qualified', 'Qualified'), ('approved', 'Approved for hire'), ('declined', 'Rejected'), ('active', 'Active driver'), ('inactive', 'Inactive / terminated'), ('archived', 'Archived')], default='applied', max_length=12),
        ),
        migrations.CreateModel(
            name='ApplicantStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(blank=True, max_length=12)),
                ('to_stage', models.CharField(max_length=12)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='operations.applicant')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
