# Generated by Django 6.1 on 2026-08-19 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0035_applicant_assigned_to_applicant_converted_driver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancedocument',
            name='review_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='compliancedocument',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('replace', 'Replacement requested')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='compliancedocument',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compliancedocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_docs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancedocument',
            name='superseded',
            field=models.BooleanField(default=False, help_text='An older version replaced by a newer upload.'),
        ),
        migrations.AddField(
            model_name='compliancedocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='compliancedocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_compliance_docs', to=settings.AUTH_USER_MODEL),
        ),
    ]
