# Generated by Django 6.1 on 2026-08-20 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0040_teammessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='address_line',
            field=models.CharField(blank=True, max_length=200, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='broker',
            name='city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='broker',
            name='state',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='broker',
            name='zip_code',
            field=models.CharField(blank=True, max_length=15, verbose_name='ZIP'),
        ),
        migrations.AlterField(
            model_name='broker',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Main phone'),
        ),
        migrations.CreateModel(
            name='BrokerAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('extension', models.CharField(blank=True, max_length=15, verbose_name='Ext.')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='operations.broker')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
