# Generated by Django 6.1 on 2026-08-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0042_load_broker_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='ratecon_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Fingerprint of the uploaded rate confirmation, to prevent duplicates.', max_length=64),
        ),
    ]
