# Generated by Django 6.1 on 2026-08-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0045_notification_taskcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='task_files/'),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
