# Generated by Django 6.1 on 2026-08-20 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0046_taskcomment_attachment_taskcomment_attachment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammessage',
            name='attachment',
            field=models.FileField(blank=True, upload_to='chat_files/'),
        ),
        migrations.AddField(
            model_name='teammessage',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='teammessage',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
