# Generated by Django 6.1 on 2026-08-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0047_teammessage_attachment_teammessage_attachment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fueltransaction',
            name='ifta_state',
            field=models.CharField(blank=True, help_text='2-letter state where fuel was purchased, e.g. CA, NV, TX.', max_length=2, verbose_name='State (for IFTA)'),
        ),
    ]
