# Generated by Django 6.1 on 2026-08-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0050_teaminvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='drivers_see_rate',
            field=models.BooleanField(default=False, help_text='If on, drivers see the dollar rate on their loads in the driver portal.', verbose_name='Drivers can see load rate ($)'),
        ),
    ]
