# Generated by Django 6.1 on 2026-08-23 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0051_company_drivers_see_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminvite',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='If set, this invite links to an existing driver record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites', to='operations.driver'),
        ),
    ]
