# Generated by Django 6.1 on 2026-08-23 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0052_teaminvite_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy', models.FloatField(blank=True, help_text='Accuracy in meters, if known.', null=True)),
                ('speed', models.FloatField(blank=True, help_text='Speed in m/s, if known.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_locations', to='operations.company')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='operations.driver')),
            ],
        ),
    ]
