# Generated by Django 6.1 on 2026-08-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0053_driverlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='track_drivers',
            field=models.BooleanField(default=False, help_text='If on, driver apps share location while open, shown on your live map.', verbose_name='Track driver location (phone GPS)'),
        ),
    ]
