# Generated by Django 6.1 on 2026-08-24 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0054_company_track_drivers'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('arrived_pickup', 'Arrived at pickup'), ('loaded', 'Loaded / picked up'), ('arrived_delivery', 'Arrived at delivery'), ('delivered', 'Delivered')], max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.driver')),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='operations.load')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
