# Generated by Django 6.1 on 2026-09-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0058_invoicelineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='check_bank_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Bank name (for checks)'),
        ),
        migrations.AddField(
            model_name='company',
            name='check_next_number',
            field=models.IntegerField(default=1001, verbose_name='Next check number'),
        ),
        migrations.AddField(
            model_name='company',
            name='check_offset_x',
            field=models.IntegerField(default=0, verbose_name='Check print offset X (points, +right/-left)'),
        ),
        migrations.AddField(
            model_name='company',
            name='check_offset_y',
            field=models.IntegerField(default=0, verbose_name='Check print offset Y (points, +down/-up)'),
        ),
        migrations.AddField(
            model_name='company',
            name='check_signature',
            field=models.CharField(blank=True, max_length=120, verbose_name='Signature line name (optional)'),
        ),
    ]
