# Generated by Django 6.1.1 on 2026-09-15 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0061_partner_expense_paid_by_partner_partnerpayback'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='pay_to_name',
            field=models.CharField(blank=True, help_text="If the driver is paid as a company (e.g. 'Singh Trucking LLC'), enter it here. Checks are made out to this name instead of the personal name.", max_length=150, verbose_name='Pay checks to (business name)'),
        ),
    ]
