# Generated by Django 6.1.1 on 2026-09-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0062_driver_pay_to_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='business_ein',
            field=models.CharField(blank=True, help_text="If you pay this driver as their company, put the company's EIN here. The 1099 uses the business name + this EIN.", max_length=20, verbose_name='Business EIN (if paid as a company)'),
        ),
    ]
