# Generated by Django 6.1.1 on 2026-09-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0064_driver_hide_load_amounts_on_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='check_amount_offset_x',
            field=models.IntegerField(default=0, verbose_name='Amount box offset X (points, +right/-left)'),
        ),
        migrations.AddField(
            model_name='company',
            name='check_amount_offset_y',
            field=models.IntegerField(default=0, verbose_name='Amount box offset Y (points, +down/-up)'),
        ),
    ]
