# Generated by Django 6.1.1 on 2026-09-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0066_company_billing_email_company_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancedocument',
            name='doc_type',
            field=models.CharField(choices=[('cdl', 'CDL license'), ('application', 'Employment application'), ('medical', 'Medical certificate'), ('mvr', 'Motor Vehicle Record (MVR)'), ('annual_review', 'Annual review of driving record'), ('psp', 'PSP report'), ('clearinghouse', 'Clearinghouse query'), ('drug_test', 'Drug / alcohol test'), ('road_test', 'Road test / CDL equivalency'), ('safety_history', 'Safety performance history'), ('eldt', 'ELDT certificate'), ('med_registry', 'Medical examiner registry verification'), ('prev_employer', 'Previous employer safety-history request/response'), ('annual_note', 'Annual review signed note'), ('cert_violations', 'Annual certificate of violations'), ('clearinghouse_annual', 'Clearinghouse annual query'), ('w9', 'W-9 (contractor)'), ('other', 'Other')], max_length=20),
        ),
    ]
