# Generated by Django 6.1.1 on 2026-09-18 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0068_alter_compliancedocument_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='accidents_3yr',
            field=models.TextField(blank=True, verbose_name="Accidents in the past 3 years — date, nature, injuries/fatalities (or 'None')"),
        ),
        migrations.AddField(
            model_name='applicant',
            name='cdl_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='CDL expiration date'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='convictions_12mo',
            field=models.TextField(blank=True, verbose_name="Traffic convictions/forfeitures in the past 12 months (or 'None')"),
        ),
        migrations.AddField(
            model_name='applicant',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='denied_suspended_details',
            field=models.TextField(blank=True, verbose_name='If yes, explain (denied/suspended/revoked)'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=200, verbose_name='Emergency contact name & phone'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='ever_denied_license',
            field=models.BooleanField(default=False, verbose_name='Ever denied a license/permit/privilege?'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='ever_suspended',
            field=models.BooleanField(default=False, verbose_name='Ever had a license suspended or revoked?'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='hazmat',
            field=models.BooleanField(default=False, verbose_name='Hazmat endorsement?'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='other_licenses',
            field=models.TextField(blank=True, verbose_name="All other licenses held in past 3 years (state, number) or 'None'"),
        ),
        migrations.AddField(
            model_name='applicant',
            name='twic',
            field=models.BooleanField(default=False, verbose_name='Has TWIC card?'),
        ),
    ]
