# Generated by Django 6.1.1 on 2026-09-18 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0069_applicant_accidents_3yr_applicant_cdl_expiry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('examiner_name', models.CharField(blank=True, max_length=120)),
                ('vehicle_type', models.CharField(blank=True, max_length=120, verbose_name='Type of equipment tested (e.g. tractor-trailer)')),
                ('pretrip', models.BooleanField(default=False, verbose_name='Pre-trip inspection')),
                ('coupling', models.BooleanField(default=False, verbose_name='Coupling & uncoupling')),
                ('placing', models.BooleanField(default=False, verbose_name='Placing equipment in operation')),
                ('controls', models.BooleanField(default=False, verbose_name='Use of vehicle controls & equipment')),
                ('braking', models.BooleanField(default=False, verbose_name='Operating in traffic, passing, braking')),
                ('turning', models.BooleanField(default=False, verbose_name='Turning the vehicle')),
                ('backing', models.BooleanField(default=False, verbose_name='Backing & parking')),
                ('slowing', models.BooleanField(default=False, verbose_name='Slowing/stopping by proper use of brakes')),
                ('passed', models.BooleanField(default=False, verbose_name='Test passed')),
                ('used_cdl_in_lieu', models.BooleanField(default=False, verbose_name='CDL accepted in lieu of road test (§391.33)')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='road_tests', to='operations.company')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='road_tests', to='operations.driver')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
