# Generated by Django 6.1.1 on 2026-09-18 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0070_roadtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='ssn_last4',
            field=models.CharField(blank=True, help_text="Only the last 4 digits are stored, for verifying the driver's identity when they e-sign.", max_length=4, verbose_name='Last 4 of SSN (for e-signature identity match)'),
        ),
        migrations.AddField(
            model_name='signaturerecord',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signature_records', to='operations.driver'),
        ),
        migrations.AddField(
            model_name='signaturerecord',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Verified by email code'),
        ),
        migrations.AddField(
            model_name='signaturerecord',
            name='ssn_last4_matched',
            field=models.BooleanField(default=False, verbose_name='Last-4 SSN matched'),
        ),
        migrations.AddField(
            model_name='signaturerecord',
            name='verified_email',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
