# Generated by Django 6.1.1 on 2026-09-18 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0071_driver_ssn_last4_signaturerecord_driver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('clearinghouse', 'FMCSA Clearinghouse full-query consent'), ('clearinghouse_limited', 'FMCSA Clearinghouse limited-query consent (annual)'), ('background', 'MVR / PSP / background & drug-alcohol records consent'), ('general', 'General application certification & consent')], max_length=24)),
                ('consent_text', models.TextField()),
                ('signer_name', models.CharField(blank=True, max_length=120)),
                ('signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('ssn_last4_matched', models.BooleanField(default=False)),
                ('verified_email', models.CharField(blank=True, max_length=254)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('email_code', models.CharField(blank=True, max_length=8)),
                ('code_sent_to', models.CharField(blank=True, max_length=254)),
                ('code_expires', models.DateTimeField(blank=True, null=True)),
                ('token', models.CharField(blank=True, db_index=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='operations.company')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='operations.driver')),
            ],
        ),
    ]
