# Generated by Django 6.1.1 on 2026-09-18 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0072_driverconsent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='rehire_date',
            field=models.DateField(blank=True, null=True, verbose_name='Most recent rehire date'),
        ),
        migrations.AddField(
            model_name='driver',
            name='termination_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last termination/leave date'),
        ),
        migrations.CreateModel(
            name='DriverEmploymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('hire', 'Hired'), ('terminate', 'Terminated / left'), ('rehire', 'Rehired')], max_length=10)),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.company')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_events', to='operations.driver')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
