# Generated by Django 6.1.1 on 2026-09-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0073_driver_rehire_date_driver_termination_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='destination',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='load',
            name='origin',
            field=models.CharField(max_length=255),
        ),
    ]
