# Generated by Django 6.1.1 on 2026-09-18 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0074_alter_load_destination_alter_load_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='co_driver',
            field=models.ForeignKey(blank=True, help_text='Second (team) driver on this load, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_driver_loads', to='operations.driver'),
        ),
    ]
