# Generated by Django 6.1.1 on 2026-09-18 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0075_load_co_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField(default=0)),
                ('kind', models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery'), ('stop', 'Stop')], default='stop', max_length=10)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('stop_date', models.DateField(blank=True, null=True)),
                ('stop_time', models.CharField(blank=True, max_length=20)),
                ('appointment', models.CharField(blank=True, max_length=60, verbose_name='Appointment / PO #')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_list', to='operations.load')),
            ],
            options={
                'ordering': ['seq', 'id'],
            },
        ),
    ]
