# Generated by Django 6.1.1 on 2026-09-21 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0079_profile_is_sales_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_number', models.CharField(max_length=20)),
                ('payee', models.CharField(max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issued_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_checks', to='operations.company')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_checks', to='operations.expense')),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_checks', to='operations.settlement')),
            ],
            options={
                'ordering': ['-issued_at'],
                'unique_together': {('company', 'check_number')},
            },
        ),
    ]
