# Generated by Django 6.1.1 on 2026-09-21 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0080_issuedcheck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuedcheck',
            name='expense',
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_check',
            field=models.ForeignKey(blank=True, help_text='Set once a check has been printed covering this expense (possibly combined with others).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='operations.issuedcheck'),
        ),
    ]
