# Generated by Django 6.1.1 on 2026-09-21 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0081_remove_issuedcheck_expense_expense_paid_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='paid_check',
            field=models.ForeignKey(blank=True, help_text='Set once a check has been printed covering this maintenance bill.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_records', to='operations.issuedcheck'),
        ),
    ]
