# Generated by Django 6.1.1 on 2026-09-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0082_maintenancerecord_paid_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='billed_at',
            field=models.DateTimeField(blank=True, help_text="Stamped automatically the first time status becomes 'invoiced'. Ages the dashboard's 'Awaiting payment' list.", null=True, verbose_name='First marked invoiced'),
        ),
        migrations.AddField(
            model_name='load',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text="Stamped automatically the first time status becomes 'delivered'. Ages the dashboard's 'Ready to bill' list.", null=True, verbose_name='First marked delivered'),
        ),
    ]
