# Generated by Django 6.1.1 on 2026-10-01 07:35

from django.db import migrations, models


# Frozen copy of operations.models.pay_method_for. Migrations must not import from
# models - that code moves on, this backfill has to keep meaning what it meant the
# day it ran.
def _method_for(factor, customer):
    if "amazon" in (customer or "").lower():
        return "Amazon Relay"
    factor = (factor or "").strip()
    return "Direct Pay" if factor in ("", "None") else factor


def backfill(apps, schema_editor):
    """Give every existing load a payment method, so nothing silently reads as
    unset. Amazon freight settles through Relay regardless of whether the company
    also factors; everything else inherits the company's factor."""
    Load = apps.get_model("operations", "Load")
    seen = {}
    for load in Load.objects.select_related("company").only(
            "id", "customer", "payment_method", "company__factor").iterator():
        if load.payment_method:
            continue
        method = _method_for(load.company.factor, load.customer)
        Load.objects.filter(pk=load.pk).update(payment_method=method)
        seen[method] = seen.get(method, 0) + 1
    if seen:
        print("\n    payment_method backfill: "
              + ", ".join(f"{k}={v}" for k, v in sorted(seen.items())))


def unfill(apps, schema_editor):
    apps.get_model("operations", "Load").objects.update(payment_method="")


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0083_load_billed_at_load_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Direct Pay', 'Direct Pay - broker/customer pays us'), ('Amazon Relay', 'Amazon Relay'), ('Quick Pay', 'Quick Pay (broker, for a fee)'), ('RTS', 'RTS Financial'), ('Bobtail', 'Bobtail'), ('TAFS', 'TAFS'), ('Apex', 'Apex Capital'), ('TBS', 'TBS Factoring'), ('OTR', 'OTR Solutions'), ('Triumph', 'Triumph Business Capital'), ('eCapital', 'eCapital'), ('Riviera', 'Riviera Finance'), ('Porter', 'Porter Freight Funding'), ('Compass', 'Compass Funding Solutions'), ('England', 'England Carrier Services'), ('Thunder', 'Thunder Funding'), ('Phoenix', 'Phoenix Capital Group'), ('Single', 'Single Point Capital'), ('Love', "Love's / TFS"), ('Other', 'Other factor / service')], help_text="Sets how long before this load is chased for payment: direct billing runs on net-30 terms, everything else settles in days. Left blank, it follows the customer and the company's factor.", max_length=20, verbose_name='How this load gets paid'),
        ),
        migrations.RunPython(backfill, unfill),
    ]
